// Generated by *go generate* - DO NOT EDIT
/*
Copyright 2022-23. projectsveltos.io. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package crd

var ConfigurationBundleFile = "../../manifests/apiextensions.k8s.io_v1_customresourcedefinition_configurationbundles.lib.projectsveltos.io.yaml"
var ConfigurationBundleCRD = []byte(`apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: configurationbundles.lib.projectsveltos.io
spec:
  group: lib.projectsveltos.io
  names:
    kind: ConfigurationBundle
    listKind: ConfigurationBundleList
    plural: configurationbundles
    singular: configurationbundle
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: ConfigurationBundle is the Schema for the configurationbundle
          API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              notTracked:
                description: |-
                  NotTracked, when true, signifies that the resources managed by the
                  ConfigurationBundles should not be tracked for conflicts
                  with other configurations and will not be automatically removed when the
                  ConfigurationGroup is deleted. This is intended for resources like
                  Sveltos CRDs or the agents Sveltos deploys in the managed clusters.
                type: boolean
              resources:
                description: |-
                  Resources contains all resources that need to be deployed.
                  Content is either YAML or JSON
                items:
                  type: string
                type: array
                x-kubernetes-list-type: atomic
            type: object
          status:
            properties:
              hash:
                description: |-
                  Hash represents of a unique value for the content stored in
                  the ConfigurationBundle
                format: byte
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
`)
