// Generated by *go generate* - DO NOT EDIT
/*
Copyright 2022-23. projectsveltos.io. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package crd

var SveltosClusterFile = "../../config/crd/bases/lib.projectsveltos.io_sveltosclusters.yaml"
var SveltosClusterCRD = []byte(`---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.12.0
  name: sveltosclusters.lib.projectsveltos.io
spec:
  group: lib.projectsveltos.io
  names:
    kind: SveltosCluster
    listKind: SveltosClusterList
    plural: sveltosclusters
    singular: sveltoscluster
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Indicates whether cluster is ready to be managed by sveltos
      jsonPath: .status.ready
      name: Ready
      type: boolean
    - description: Kubernetes version associated with this Cluster
      jsonPath: .status.version
      name: Version
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: SveltosCluster is the Schema for the SveltosCluster API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: SveltosClusterSpec defines the desired state of SveltosCluster
            properties:
              paused:
                description: Paused can be used to prevent controllers from processing
                  the SveltosCluster and all its associated objects.
                type: boolean
            type: object
          status:
            description: SveltosClusterStatus defines the status of SveltosCluster
            properties:
              failureMessage:
                description: FailureMessage is a human consumable message explaining
                  the misconfiguration
                type: string
              ready:
                description: Ready is the state of the cluster.
                type: boolean
              version:
                description: The Kubernetes version of the cluster.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
`)
